#!/bin/sh
# dwm-titus autostart — single unified autostart script
# Phase 1: Blocking setup (must complete before windows appear)
# Phase 2: Background services (compositor, notifications, polybar, tray apps)

# ── Phase 1: Blocking ──────────────────────────────────────────────────────────
# Disable DPMS and screen blanking (prevents GPU/display wake issues)
xset s off
xset s noblank
xset -dpms

# Export display env to session manager/dbus in parallel (both are IPC round-trips)
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user import-environment DISPLAY XAUTHORITY &
fi
# On Void Linux (runit/elogind), --systemd flag is not available; omit it
if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    if command -v systemctl >/dev/null 2>&1; then
        dbus-update-activation-environment --systemd DISPLAY XAUTHORITY 2>/dev/null &
    else
        dbus-update-activation-environment DISPLAY XAUTHORITY 2>/dev/null &
    fi
fi
wait

# ── Phase 2: Background services ───────────────────────────────────────────────


# Source theme environment so tray apps (e.g. flameshot) inherit QT_QPA_PLATFORMTHEME
# This file is generated by theme-apply.sh and updated on every theme change.
THEME_ENV="${XDG_CONFIG_HOME:-$HOME/.config}/dwm-titus/theme-env.sh"
[ -f "$THEME_ENV" ] && . "$THEME_ENV"

# Wallpaper (moved here from Phase 1 — does not need to block dwm startup)
feh --randomize --bg-fill ~/Pictures/backgrounds/* 2>/dev/null &

# Compositor
picom -b 2>/dev/null &

# Notification daemon
dunst 2>/dev/null &

# PipeWire audio (needed on non-systemd systems; harmless on systemd if already running)
if command -v pipewire &>/dev/null && ! pgrep -x pipewire &>/dev/null; then
    pipewire 2>/dev/null &
    sleep 0.5
    if command -v wireplumber &>/dev/null; then
        wireplumber 2>/dev/null &
    elif command -v pipewire-media-session &>/dev/null; then
        pipewire-media-session 2>/dev/null &
    fi
    if command -v pipewire-pulse &>/dev/null; then
        pipewire-pulse 2>/dev/null &
    fi
fi

# Polkit authentication agent (try common agents)
for agent in \
    /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 \
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 \
    /usr/libexec/polkit-gnome-authentication-agent-1 \
    /usr/lib/polkit-kde-authentication-agent-1 \
    /usr/libexec/polkit-kde-authentication-agent-1 \
    /usr/bin/lxpolkit \
    /usr/lib/lxpolkit/lxpolkit; do
    if [ -x "$agent" ]; then
        "$agent" &
        break
    fi
done

# Launch Polybar
"$HOME/.config/polybar/launch.sh" 2>/dev/null &

dex -a 2>/dev/null
