#!/bin/bash
# theme-apply.sh — Apply the active theme from themes.toml to all apps.

set -euo pipefail

THEMES_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/dwm-titus/themes.toml"
if [[ ! -f "$THEMES_FILE" ]]; then
    echo "theme-apply: themes.toml not found at $THEMES_FILE" >&2
    exit 1
fi

toml_get() {
    local section="$1" key="$2" file="$3"
    awk -v sec="[$section]" -v key="$key" '
        /^\[/ { in_sec = ($0 == sec) }
        in_sec && $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
            sub(/^[^=]*=[[:space:]]*/, "")
            gsub(/"/, "")
            gsub(/[[:space:]]+#.*$/, "")  # strip inline comments (not # in hex colors)
            sub(/[[:space:]]+$/, "")
            print; exit
        }
    ' "$file"
}

THEME_NAME="$(toml_get "active" "theme" "$THEMES_FILE")"
if [[ -z "$THEME_NAME" ]]; then
    echo "theme-apply: no [active] theme set in $THEMES_FILE" >&2
    exit 1
fi

SECTION="theme.$THEME_NAME"

theme_get() {
    toml_get "$SECTION" "$1" "$THEMES_FILE"
}

TERM_BG="$(theme_get term_bg)"
TERM_FG="$(theme_get term_fg)"
TERM_CURSOR="$(theme_get term_cursor)"
TERM_C0="$(theme_get term_color0)"
TERM_C1="$(theme_get term_color1)"
TERM_C2="$(theme_get term_color2)"
TERM_C3="$(theme_get term_color3)"
TERM_C4="$(theme_get term_color4)"
TERM_C5="$(theme_get term_color5)"
TERM_C6="$(theme_get term_color6)"
TERM_C7="$(theme_get term_color7)"
TERM_C8="$(theme_get term_color8)"
TERM_C9="$(theme_get term_color9)"
TERM_C10="$(theme_get term_color10)"
TERM_C11="$(theme_get term_color11)"
TERM_C12="$(theme_get term_color12)"
TERM_C13="$(theme_get term_color13)"
TERM_C14="$(theme_get term_color14)"
TERM_C15="$(theme_get term_color15)"

ROFI_THEME="$(theme_get rofi_theme)"
GTK_THEME="$(theme_get gtk_theme)"

PB_BG="$(theme_get polybar_bg)"
PB_FG="$(theme_get polybar_fg)"
PB_BG_ALT="$(theme_get polybar_bg_alt)"
PB_FG_ALT="$(theme_get polybar_fg_alt)"
PB_ACCENT="$(theme_get polybar_accent)"
PB_URGENT="$(theme_get polybar_urgent)"

DARK_MODE="$(theme_get dark_mode)"
[[ "$DARK_MODE" != "false" ]] && DARK_MODE="true"  # default to dark if unset


ALACRITTY_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/alacritty"
if [[ -d "$ALACRITTY_DIR" ]]; then
    cat > "$ALACRITTY_DIR/active-theme.toml" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
# Change the theme in ~/.config/dwm-titus/themes.toml instead.

[colors.primary]
background = '$TERM_BG'
foreground = '$TERM_FG'

[colors.cursor]
text   = '$TERM_BG'
cursor = '$TERM_CURSOR'

[colors.normal]
black   = '$TERM_C0'
red     = '$TERM_C1'
green   = '$TERM_C2'
yellow  = '$TERM_C3'
blue    = '$TERM_C4'
magenta = '$TERM_C5'
cyan    = '$TERM_C6'
white   = '$TERM_C7'

[colors.bright]
black   = '$TERM_C8'
red     = '$TERM_C9'
green   = '$TERM_C10'
yellow  = '$TERM_C11'
blue    = '$TERM_C12'
magenta = '$TERM_C13'
cyan    = '$TERM_C14'
white   = '$TERM_C15'
EOF

    # Ensure alacritty.toml imports active-theme.toml (add if missing)
    if [[ -f "$ALACRITTY_DIR/alacritty.toml" ]]; then
        if ! grep -q "active-theme.toml" "$ALACRITTY_DIR/alacritty.toml"; then
            # Insert active-theme.toml as first import entry
            sed -i 's|^\(import = \[\s*\)|\1\n  "~/.config/alacritty/active-theme.toml",|' \
                "$ALACRITTY_DIR/alacritty.toml"
        fi
        # Replace any existing theme import line to point to active-theme.toml
        # (removes old theme-specific imports, keeps keybinds import)
        sed -i 's|"~/.config/alacritty/[^k][^"]*\.toml"|"~/.config/alacritty/active-theme.toml"|g' \
            "$ALACRITTY_DIR/alacritty.toml"
    fi
fi


KITTY_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
if [[ -d "$KITTY_DIR" ]]; then
    cat > "$KITTY_DIR/active-theme.conf" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
# Change the theme in ~/.config/dwm-titus/themes.toml instead.

background  $TERM_BG
foreground  $TERM_FG
cursor      $TERM_CURSOR

color0  $TERM_C0
color1  $TERM_C1
color2  $TERM_C2
color3  $TERM_C3
color4  $TERM_C4
color5  $TERM_C5
color6  $TERM_C6
color7  $TERM_C7
color8  $TERM_C8
color9  $TERM_C9
color10 $TERM_C10
color11 $TERM_C11
color12 $TERM_C12
color13 $TERM_C13
color14 $TERM_C14
color15 $TERM_C15
EOF

    # Ensure kitty.conf has 'include active-theme.conf' at the top
    if [[ -f "$KITTY_DIR/kitty.conf" ]]; then
        if ! grep -q "include active-theme.conf" "$KITTY_DIR/kitty.conf"; then
            sed -i '1s|^|include active-theme.conf\n|' "$KITTY_DIR/kitty.conf"
        fi
    fi

    # Signal kitty to reload (no restart needed)
    if command -v kitty &>/dev/null; then
        kill -SIGUSR1 "$(pgrep -x kitty)" 2>/dev/null || true
    fi
fi


ROFI_CFG="${XDG_CONFIG_HOME:-$HOME/.config}/rofi/config.rasi"
if [[ -n "$ROFI_THEME" && -f "$ROFI_CFG" ]]; then
    if grep -q '@theme' "$ROFI_CFG"; then
        sed -i "s|@theme \".*\"|@theme \"themes/$ROFI_THEME.rasi\"|g" "$ROFI_CFG"
    else
        echo "@theme \"themes/$ROFI_THEME.rasi\"" >> "$ROFI_CFG"
    fi
fi


PB_COLORS="${XDG_CONFIG_HOME:-$HOME/.config}/polybar/themes/minimal/colors.ini"
if [[ -n "$PB_BG" ]]; then
    mkdir -p "$(dirname "$PB_COLORS")"
    # Overwrite the entire file — guarantees consistency across all installs.
    cat > "$PB_COLORS" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
# Change the theme in ~/.config/dwm-titus/themes.toml instead.

[colors]
bg               = $PB_BG
fg               = $PB_FG
bg-alt           = $PB_BG_ALT
fg-alt           = $PB_FG_ALT

blue             = $PB_ACCENT
red              = $PB_URGENT

; These values are computed from the theme's terminal palette.
; Polybar modules that reference \${colors.cyan}, \${colors.green} etc. will
; fall back to the accent/urgent colours above if a theme doesn't define them.
cyan             = $PB_ACCENT
green            = $PB_ACCENT
orange           = $PB_URGENT
pink             = $PB_ACCENT
purple           = $PB_ACCENT
yellow           = $PB_ACCENT

black            = $PB_BG
white            = $PB_FG

trans            = #00000000
semi-trans-black = #aa000000
EOF

    # Restart polybar to pick up the new colors
    if command -v polybar &>/dev/null; then
        POLYBAR_LAUNCH="${XDG_CONFIG_HOME:-$HOME/.config}/polybar/launch.sh"
        if [[ -x "$POLYBAR_LAUNCH" ]]; then
            "$POLYBAR_LAUNCH" &
        fi
    fi
fi


if [[ "$DARK_MODE" == "true" ]]; then
    GTK_COLOR_SCHEME="prefer-dark"
    GTK_DARK_PREF=1
else
    GTK_COLOR_SCHEME="default"
    GTK_DARK_PREF=0
fi

# Use gtk_theme from themes.toml, fallback to Adwaita
if [[ -n "$GTK_THEME" ]]; then
    GTK_THEME_NAME="$GTK_THEME"
elif [[ "$DARK_MODE" == "true" ]]; then
    GTK_THEME_NAME="Adwaita-dark"
else
    GTK_THEME_NAME="Adwaita"
fi

gtk_ini_set() {
    local file="$1" key="$2" value="$3"
    mkdir -p "$(dirname "$file")"
    if [[ ! -f "$file" ]]; then
        printf '[Settings]\n%s=%s\n' "$key" "$value" > "$file"
        return
    fi
    if grep -q "^${key}" "$file"; then
        sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    elif grep -q '^\[Settings\]' "$file"; then
        sed -i "/^\[Settings\]/a ${key}=${value}" "$file"
    else
        printf '\n[Settings]\n%s=%s\n' "$key" "$value" >> "$file"
    fi
}

# GTK3
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini" \
    "gtk-application-prefer-dark-theme" "$GTK_DARK_PREF"
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini" \
    "gtk-theme-name" "$GTK_THEME_NAME"

# GTK4
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0/settings.ini" \
    "gtk-application-prefer-dark-theme" "$GTK_DARK_PREF"
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0/settings.ini" \
    "gtk-theme-name" "$GTK_THEME_NAME"

# Copy/symlink gtk-4.0 theme folder assets so GTK4 applications can render the theme
if [[ -d "$HOME/.themes/$GTK_THEME_NAME/gtk-4.0" ]]; then
    mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0"
    cp -rf "$HOME/.themes/$GTK_THEME_NAME/gtk-4.0/"* "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0/" 2>/dev/null || true
fi

# GTK2
printf 'gtk-theme-name="%s"\n' "$GTK_THEME_NAME" > "$HOME/.gtkrc-2.0"

# Live D-Bus update — affects running GTK4 apps, Flatpaks, and XDG portals
if command -v gsettings &>/dev/null; then
    gsettings set org.gnome.desktop.interface color-scheme "$GTK_COLOR_SCHEME" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface gtk-theme    "$GTK_THEME_NAME"   2>/dev/null || true
fi


# Prefer qt6ct > qt5ct; fall back to gtk3
if command -v qt6ct &>/dev/null; then
    QT_PLATFORM_THEME="qt6ct"
elif command -v qt5ct &>/dev/null; then
    QT_PLATFORM_THEME="qt5ct"
else
    QT_PLATFORM_THEME="gtk3"
fi

# Write persistent env file — sourced by autostart.sh so tray apps inherit it
THEME_ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/dwm-titus/theme-env.sh"
cat > "$THEME_ENV_FILE" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
export QT_QPA_PLATFORMTHEME="$QT_PLATFORM_THEME"
export GTK_THEME="$GTK_THEME_NAME"
EOF

qt_ct_init() {
    local dir="$1" conf="$2" scheme="$3"
    mkdir -p "$dir"
    if [[ ! -f "$conf" ]]; then
        cat > "$conf" <<EOF
[Appearance]
color_scheme_path=$scheme
custom_palette=true
style=Fusion
EOF
    else
        # Ensure Appearance section exists
        if ! grep -q '^\[Appearance\]' "$conf"; then
            printf '\n[Appearance]\n' >> "$conf"
        fi
        # Set or replace color_scheme_path
        if grep -q '^color_scheme_path' "$conf"; then
            sed -i "s|^color_scheme_path=.*|color_scheme_path=$scheme|" "$conf"
        else
            sed -i "/^\[Appearance\]/a color_scheme_path=$scheme" "$conf"
        fi
        # Ensure custom_palette=true is set
        if grep -q '^custom_palette' "$conf"; then
            sed -i "s|^custom_palette=.*|custom_palette=true|" "$conf"
        else
            sed -i "/^\[Appearance\]/a custom_palette=true" "$conf"
        fi
        # Ensure style=Fusion or similar is set if style is empty or not set
        if ! grep -q '^style' "$conf"; then
            sed -i "/^\[Appearance\]/a style=Fusion" "$conf"
        fi
    fi
}

# Update qt5ct / qt6ct color scheme config if that tool is the active theme
if [[ "$QT_PLATFORM_THEME" == "qt5ct" || "$QT_PLATFORM_THEME" == "qt6ct" ]]; then
    QT_CT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/${QT_PLATFORM_THEME}"
    QT_CT_CONF="${QT_CT_DIR}/${QT_PLATFORM_THEME}.conf"
    QT_CT_SCHEME=""

    # Generate a gruvbox color scheme if the theme contains "gruvbox"
    if [[ "$GTK_THEME" == *gruvbox* || "$GTK_THEME" == *Gruvbox* ]]; then
        QT_CT_SCHEME="${QT_CT_DIR}/colors/gruvbox-dark-hard.conf"
        mkdir -p "${QT_CT_DIR}/colors"
        cat > "$QT_CT_SCHEME" <<QTEOF
[ColorScheme]
active_colors=#ff1d2021, #ffebdbb2, #ff1d2021, #ff504945, #ffcc241d, #ffb16286, #ff98971a, #ffebdbb2, #fffabd2f, #fffbf1c7, #ff1d2021, #ffebdbb2, #ff458588, #ffebdbb2, #ff689d6a, #ff1d2021, #ffebdbb2, #fffb4934, #ff1d2021, #fffabd2f
disabled_colors=#ff1d2021, #ff928374, #ff1d2021, #ff504945, #ffcc241d, #ffb16286, #ff98971a, #ff928374, #fffabd2f, #fffbf1c7, #ff1d2021, #ff928374, #ff458588, #ff928374, #ff689d6a, #ff1d2021, #ff928374, #fffb4934, #ff1d2021, #fffabd2f
inactive_colors=#ff1d2021, #ffebdbb2, #ff1d2021, #ff504945, #ffcc241d, #ffb16286, #ff98971a, #ffebdbb2, #fffabd2f, #fffbf1c7, #ff1d2021, #ffebdbb2, #ff458588, #ffebdbb2, #ff689d6a, #ff1d2021, #ffebdbb2, #fffb4934, #ff1d2021, #fffabd2f
QTEOF
    elif [[ "$DARK_MODE" == "true" ]]; then
        QT_CT_SCHEME="/usr/share/${QT_PLATFORM_THEME}/colors/darker.conf"
    fi

    if [[ -n "$QT_CT_SCHEME" ]]; then
        qt_ct_init "$QT_CT_DIR" "$QT_CT_CONF" "$QT_CT_SCHEME"
    fi
fi

# Propagate to D-Bus-activated services already running in this session
if command -v dbus-update-activation-environment &>/dev/null; then
    dbus-update-activation-environment QT_QPA_PLATFORMTHEME="$QT_PLATFORM_THEME" GTK_THEME="$GTK_THEME_NAME" 2>/dev/null || true
fi

# Restart flameshot so its tray icon picks up the new theme
if pgrep -x flameshot &>/dev/null; then
    pkill -x flameshot 2>/dev/null || true
    sleep 0.3
    QT_QPA_PLATFORMTHEME="$QT_PLATFORM_THEME" GTK_THEME="$GTK_THEME_NAME" flameshot &
fi


echo "theme-apply: applied theme '$THEME_NAME'"
